import { UnknownCurrencyError } from './errors'

export interface CurrencyInfo {
  code: string
  decimals: number
  symbol: string
  name: string
}

const REGISTRY: Record<string, CurrencyInfo> = {
  // Major currencies
  USD: { code: 'USD', decimals: 2, symbol: '$', name: 'US Dollar' },
  EUR: { code: 'EUR', decimals: 2, symbol: '€', name: 'Euro' },
  GBP: { code: 'GBP', decimals: 2, symbol: '£', name: 'British Pound' },
  AUD: { code: 'AUD', decimals: 2, symbol: 'A$', name: 'Australian Dollar' },
  CAD: { code: 'CAD', decimals: 2, symbol: 'CA$', name: 'Canadian Dollar' },
  CHF: { code: 'CHF', decimals: 2, symbol: 'Fr', name: 'Swiss Franc' },
  CNY: { code: 'CNY', decimals: 2, symbol: '¥', name: 'Chinese Yuan' },
  HKD: { code: 'HKD', decimals: 2, symbol: 'HK$', name: 'Hong Kong Dollar' },
  NZD: { code: 'NZD', decimals: 2, symbol: 'NZ$', name: 'New Zealand Dollar' },
  SEK: { code: 'SEK', decimals: 2, symbol: 'kr', name: 'Swedish Krona' },
  NOK: { code: 'NOK', decimals: 2, symbol: 'kr', name: 'Norwegian Krone' },
  DKK: { code: 'DKK', decimals: 2, symbol: 'kr', name: 'Danish Krone' },
  SGD: { code: 'SGD', decimals: 2, symbol: 'S$', name: 'Singapore Dollar' },
  MXN: { code: 'MXN', decimals: 2, symbol: 'MX$', name: 'Mexican Peso' },
  BRL: { code: 'BRL', decimals: 2, symbol: 'R$', name: 'Brazilian Real' },
  INR: { code: 'INR', decimals: 2, symbol: '₹', name: 'Indian Rupee' },
  RUB: { code: 'RUB', decimals: 2, symbol: '₽', name: 'Russian Ruble' },
  ZAR: { code: 'ZAR', decimals: 2, symbol: 'R', name: 'South African Rand' },
  TRY: { code: 'TRY', decimals: 2, symbol: '₺', name: 'Turkish Lira' },
  ARS: { code: 'ARS', decimals: 2, symbol: 'AR$', name: 'Argentine Peso' },
  PLN: { code: 'PLN', decimals: 2, symbol: 'zł', name: 'Polish Zloty' },
  CZK: { code: 'CZK', decimals: 2, symbol: 'Kč', name: 'Czech Koruna' },
  HUF: { code: 'HUF', decimals: 2, symbol: 'Ft', name: 'Hungarian Forint' },
  RON: { code: 'RON', decimals: 2, symbol: 'lei', name: 'Romanian Leu' },
  HRK: { code: 'HRK', decimals: 2, symbol: 'kn', name: 'Croatian Kuna' },
  BGN: { code: 'BGN', decimals: 2, symbol: 'лв', name: 'Bulgarian Lev' },
  MYR: { code: 'MYR', decimals: 2, symbol: 'RM', name: 'Malaysian Ringgit' },
  IDR: { code: 'IDR', decimals: 2, symbol: 'Rp', name: 'Indonesian Rupiah' },
  PHP: { code: 'PHP', decimals: 2, symbol: '₱', name: 'Philippine Peso' },
  THB: { code: 'THB', decimals: 2, symbol: '฿', name: 'Thai Baht' },
  PKR: { code: 'PKR', decimals: 2, symbol: '₨', name: 'Pakistani Rupee' },
  EGP: { code: 'EGP', decimals: 2, symbol: 'E£', name: 'Egyptian Pound' },
  NGN: { code: 'NGN', decimals: 2, symbol: '₦', name: 'Nigerian Naira' },
  UAH: { code: 'UAH', decimals: 2, symbol: '₴', name: 'Ukrainian Hryvnia' },
  AED: { code: 'AED', decimals: 2, symbol: 'د.إ', name: 'UAE Dirham' },
  SAR: { code: 'SAR', decimals: 2, symbol: '﷼', name: 'Saudi Riyal' },
  QAR: { code: 'QAR', decimals: 2, symbol: '﷼', name: 'Qatari Riyal' },
  MAD: { code: 'MAD', decimals: 2, symbol: 'MAD', name: 'Moroccan Dirham' },
  COP: { code: 'COP', decimals: 2, symbol: 'CO$', name: 'Colombian Peso' },
  PEN: { code: 'PEN', decimals: 2, symbol: 'S/', name: 'Peruvian Sol' },
  CLP: { code: 'CLP', decimals: 0, symbol: 'CL$', name: 'Chilean Peso' },
  TWD: { code: 'TWD', decimals: 2, symbol: 'NT$', name: 'New Taiwan Dollar' },
  ILS: { code: 'ILS', decimals: 2, symbol: '₪', name: 'Israeli New Shekel' },
  MKD: { code: 'MKD', decimals: 2, symbol: 'ден', name: 'Macedonian Denar' },
  GEL: { code: 'GEL', decimals: 2, symbol: '₾', name: 'Georgian Lari' },
  AMD: { code: 'AMD', decimals: 2, symbol: '֏', name: 'Armenian Dram' },
  AZN: { code: 'AZN', decimals: 2, symbol: '₼', name: 'Azerbaijani Manat' },
  BYN: { code: 'BYN', decimals: 2, symbol: 'Br', name: 'Belarusian Ruble' },
  KZT: { code: 'KZT', decimals: 2, symbol: '₸', name: 'Kazakhstani Tenge' },
  UZS: { code: 'UZS', decimals: 2, symbol: 'so\'m', name: 'Uzbekistani Som' },
  AFN: { code: 'AFN', decimals: 2, symbol: '؋', name: 'Afghan Afghani' },
  ALL: { code: 'ALL', decimals: 2, symbol: 'L', name: 'Albanian Lek' },
  DZD: { code: 'DZD', decimals: 2, symbol: 'DA', name: 'Algerian Dinar' },
  AOA: { code: 'AOA', decimals: 2, symbol: 'Kz', name: 'Angolan Kwanza' },
  XCD: { code: 'XCD', decimals: 2, symbol: 'EC$', name: 'East Caribbean Dollar' },
  BBD: { code: 'BBD', decimals: 2, symbol: 'Bds$', name: 'Barbadian Dollar' },
  BDT: { code: 'BDT', decimals: 2, symbol: '৳', name: 'Bangladeshi Taka' },
  BSD: { code: 'BSD', decimals: 2, symbol: 'B$', name: 'Bahamian Dollar' },
  BND: { code: 'BND', decimals: 2, symbol: 'B$', name: 'Brunei Dollar' },
  BOB: { code: 'BOB', decimals: 2, symbol: 'Bs.', name: 'Bolivian Boliviano' },
  BAM: { code: 'BAM', decimals: 2, symbol: 'KM', name: 'Bosnia-Herzegovina Convertible Mark' },
  BWP: { code: 'BWP', decimals: 2, symbol: 'P', name: 'Botswana Pula' },
  BZD: { code: 'BZD', decimals: 2, symbol: 'BZ$', name: 'Belize Dollar' },
  XOF: { code: 'XOF', decimals: 0, symbol: 'CFA', name: 'West African CFA Franc' },
  XAF: { code: 'XAF', decimals: 0, symbol: 'FCFA', name: 'Central African CFA Franc' },
  KHR: { code: 'KHR', decimals: 2, symbol: '៛', name: 'Cambodian Riel' },
  CVE: { code: 'CVE', decimals: 2, symbol: 'CV$', name: 'Cape Verdean Escudo' },
  KYD: { code: 'KYD', decimals: 2, symbol: 'CI$', name: 'Cayman Islands Dollar' },
  DJF: { code: 'DJF', decimals: 0, symbol: 'Fdj', name: 'Djiboutian Franc' },
  DOP: { code: 'DOP', decimals: 2, symbol: 'RD$', name: 'Dominican Peso' },
  ERN: { code: 'ERN', decimals: 2, symbol: 'Nfk', name: 'Eritrean Nakfa' },
  ETB: { code: 'ETB', decimals: 2, symbol: 'Br', name: 'Ethiopian Birr' },
  FJD: { code: 'FJD', decimals: 2, symbol: 'FJ$', name: 'Fijian Dollar' },
  GMD: { code: 'GMD', decimals: 2, symbol: 'D', name: 'Gambian Dalasi' },
  GTQ: { code: 'GTQ', decimals: 2, symbol: 'Q', name: 'Guatemalan Quetzal' },
  GNF: { code: 'GNF', decimals: 0, symbol: 'FG', name: 'Guinean Franc' },
  GYD: { code: 'GYD', decimals: 2, symbol: 'GY$', name: 'Guyanese Dollar' },
  HTG: { code: 'HTG', decimals: 2, symbol: 'G', name: 'Haitian Gourde' },
  HNL: { code: 'HNL', decimals: 2, symbol: 'L', name: 'Honduran Lempira' },
  ISK: { code: 'ISK', decimals: 0, symbol: 'kr', name: 'Icelandic Króna' },
  JMD: { code: 'JMD', decimals: 2, symbol: 'J$', name: 'Jamaican Dollar' },
  JPY: { code: 'JPY', decimals: 0, symbol: '¥', name: 'Japanese Yen' },
  JOD: { code: 'JOD', decimals: 3, symbol: 'JD', name: 'Jordanian Dinar' },
  KES: { code: 'KES', decimals: 2, symbol: 'KSh', name: 'Kenyan Shilling' },
  KPW: { code: 'KPW', decimals: 2, symbol: '₩', name: 'North Korean Won' },
  KRW: { code: 'KRW', decimals: 0, symbol: '₩', name: 'South Korean Won' },
  KGS: { code: 'KGS', decimals: 2, symbol: 'лв', name: 'Kyrgyzstani Som' },
  LAK: { code: 'LAK', decimals: 2, symbol: '₭', name: 'Lao Kip' },
  LBP: { code: 'LBP', decimals: 2, symbol: 'L£', name: 'Lebanese Pound' },
  LSL: { code: 'LSL', decimals: 2, symbol: 'M', name: 'Lesotho Loti' },
  LRD: { code: 'LRD', decimals: 2, symbol: 'L$', name: 'Liberian Dollar' },
  LYD: { code: 'LYD', decimals: 3, symbol: 'LD', name: 'Libyan Dinar' },
  MOP: { code: 'MOP', decimals: 2, symbol: 'MOP$', name: 'Macanese Pataca' },
  MWK: { code: 'MWK', decimals: 2, symbol: 'MK', name: 'Malawian Kwacha' },
  MVR: { code: 'MVR', decimals: 2, symbol: 'Rf', name: 'Maldivian Rufiyaa' },
  MRU: { code: 'MRU', decimals: 2, symbol: 'UM', name: 'Mauritanian Ouguiya' },
  MUR: { code: 'MUR', decimals: 2, symbol: '₨', name: 'Mauritian Rupee' },
  MNT: { code: 'MNT', decimals: 2, symbol: '₮', name: 'Mongolian Tögrög' },
  MZN: { code: 'MZN', decimals: 2, symbol: 'MT', name: 'Mozambican Metical' },
  NAD: { code: 'NAD', decimals: 2, symbol: 'N$', name: 'Namibian Dollar' },
  NPR: { code: 'NPR', decimals: 2, symbol: '₨', name: 'Nepalese Rupee' },
  NIO: { code: 'NIO', decimals: 2, symbol: 'C$', name: 'Nicaraguan Córdoba' },
  XPF: { code: 'XPF', decimals: 0, symbol: 'Fr', name: 'CFP Franc' },
  OMR: { code: 'OMR', decimals: 3, symbol: '﷼', name: 'Omani Rial' },
  KWD: { code: 'KWD', decimals: 3, symbol: 'KD', name: 'Kuwaiti Dinar' },
  BHD: { code: 'BHD', decimals: 3, symbol: 'BD', name: 'Bahraini Dinar' },
  IQD: { code: 'IQD', decimals: 3, symbol: 'ع.د', name: 'Iraqi Dinar' },
  TND: { code: 'TND', decimals: 3, symbol: 'DT', name: 'Tunisian Dinar' },
  CLF: { code: 'CLF', decimals: 4, symbol: 'UF', name: 'Chilean Unit of Account (UF)' },
  UYW: { code: 'UYW', decimals: 4, symbol: 'UYW', name: 'Uruguayan Nominal Wage Index Unit' },
  UYU: { code: 'UYU', decimals: 2, symbol: '$U', name: 'Uruguayan Peso' },
  PGK: { code: 'PGK', decimals: 2, symbol: 'K', name: 'Papua New Guinean Kina' },
  PYG: { code: 'PYG', decimals: 0, symbol: '₲', name: 'Paraguayan Guaraní' },
  RWF: { code: 'RWF', decimals: 0, symbol: 'RF', name: 'Rwandan Franc' },
  WST: { code: 'WST', decimals: 2, symbol: 'WS$', name: 'Samoan Tālā' },
  STN: { code: 'STN', decimals: 2, symbol: 'Db', name: 'São Tomé and Príncipe Dobra' },
  SLL: { code: 'SLL', decimals: 2, symbol: 'Le', name: 'Sierra Leonean Leone' },
  SOS: { code: 'SOS', decimals: 2, symbol: 'Sh', name: 'Somali Shilling' },
  SRD: { code: 'SRD', decimals: 2, symbol: '$', name: 'Surinamese Dollar' },
  SZL: { code: 'SZL', decimals: 2, symbol: 'L', name: 'Swazi Lilangeni' },
  TJS: { code: 'TJS', decimals: 2, symbol: 'SM', name: 'Tajikistani Somoni' },
  TZS: { code: 'TZS', decimals: 2, symbol: 'TSh', name: 'Tanzanian Shilling' },
  TOP: { code: 'TOP', decimals: 2, symbol: 'T$', name: 'Tongan Paʻanga' },
  TTD: { code: 'TTD', decimals: 2, symbol: 'TT$', name: 'Trinidad and Tobago Dollar' },
  TMT: { code: 'TMT', decimals: 2, symbol: 'T', name: 'Turkmenistani Manat' },
  UGX: { code: 'UGX', decimals: 0, symbol: 'USh', name: 'Ugandan Shilling' },
  VUV: { code: 'VUV', decimals: 0, symbol: 'VT', name: 'Vanuatu Vatu' },
  VES: { code: 'VES', decimals: 2, symbol: 'Bs.S', name: 'Venezuelan Bolívar Soberano' },
  VND: { code: 'VND', decimals: 0, symbol: '₫', name: 'Vietnamese Đồng' },
  YER: { code: 'YER', decimals: 2, symbol: '﷼', name: 'Yemeni Rial' },
  ZMW: { code: 'ZMW', decimals: 2, symbol: 'ZK', name: 'Zambian Kwacha' },
  ZWL: { code: 'ZWL', decimals: 2, symbol: 'Z$', name: 'Zimbabwean Dollar' },
  // Crypto
  BTC: { code: 'BTC', decimals: 8, symbol: '₿', name: 'Bitcoin' },
  ETH: { code: 'ETH', decimals: 18, symbol: 'Ξ', name: 'Ethereum' },
  USDC: { code: 'USDC', decimals: 6, symbol: 'USDC', name: 'USD Coin' },
  USDT: { code: 'USDT', decimals: 6, symbol: '₮', name: 'Tether' },
}

export function currencyInfo(code: string): CurrencyInfo {
  const info = REGISTRY[code]
  if (!info) throw new UnknownCurrencyError(code)
  return info
}

export function isCurrency(code: string): boolean {
  return Object.prototype.hasOwnProperty.call(REGISTRY, code)
}

export function registerCurrency(info: CurrencyInfo): void {
  REGISTRY[info.code] = info
}
